/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    Mobile mobileIphone = new Iphone("zr", "red", "apple");
    mobileIphone.printMessage("11");
    Mobile mobileAndroid = new AndriodPhone("zr", "red", "huawei");
    mobileAndroid.printMessage("22");
    Person firstPerson = new Person(new Iphone("zr1", "red", "apple"));
    firstPerson.printMessage("p1");
    Person secondPerson = new Person(new AndriodPhone("zr2", "yellow", "huawei"));
    secondPerson.printMessage("p2");
  }
}
