/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
//    System.out.println(new App().getGreeting());

    Mobile mobileIphone = new Iphone("zr", "red", "apple");
    mobileIphone.printMessage("11");
    Mobile andriodPhone = new AndriodPhone("zr", "red", "huawei");
    andriodPhone.printMessage("22");
  }
}
